name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clear known hosts file
        run: |
          rm -f $HOME/.ssh/known_hosts

      - name: Verify EC2 host key
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Set permissions on SSH private key
        run: chmod 600 $HOME/.ssh/known_hosts
        
      - name: Copy files to EC2 instance
        run: scp -r ./metadata_ingestion ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/MyDataHubProject
        # This step always runs since it copies files

      - name: Run DataHub ingest command for creating business glossary terms/term groups
        if: ${{ github.event_name == 'push' && needs_update(github.event.commits, '/home/ubuntu/MyDataHubProject/glossary_yaml_ingestion') }}
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/MyDataHubProject/glossary_yaml_ingestion && cat recipe.yml"

      - name: Run DataHub ingest command for mapping terms/tags to snowflake entity
        if: ${{ github.event_name == 'push' && needs_update(github.event.commits, '/home/ubuntu/MyDataHubProject/map_csv_ingestion') }}
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/MyDataHubProject/map_csv_ingestion && cat recipe.yml"

# Function to check if a specific directory has been updated in any commit
# Returns true if any commit contains changes in the specified directory, otherwise false
# Commits is the array of commit objects in the push event
# Directory is the path to the directory to check for updates
# Note: This function needs to be implemented using a custom action or script
# since GitHub Actions YAML does not support custom functions directly.
