name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clear known hosts file
        run: |
          rm -f $HOME/.ssh/known_hosts

      - name: Verify EC2 host key
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Set permissions on SSH private key
        run: chmod 600 $HOME/.ssh/known_hosts
        
      - name: Copy files to EC2 instance
        run: scp -r ./metadata_ingestion ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/MyDataHubProject
        # This step always runs since it copies files

      - name: Check for changes in glossary_yaml_ingestion
        id: glossary_changes
        run: |
          if git diff --quiet --exit-code HEAD^ -- /home/ubuntu/MyDataHubProject/glossary_yaml_ingestion; then
            echo "No changes in glossary_yaml_ingestion"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected in glossary_yaml_ingestion"
            echo "::set-output name=changes::true"
          fi

      - name: Run DataHub ingest command for creating business glossary terms/term group
        if: ${{ github.event_name == 'push' && steps.glossary_changes.outputs.changes == 'true' }}
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/MyDataHubProject/glossary_yaml_ingestion && cat recipe.yml"

      # Add a similar block for the map_csv_ingestion directory
