name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clear known hosts file
        run: |
          rm -f $HOME/.ssh/known_hosts

      - name: Verify EC2 host key
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Set permissions on SSH private key
        run: chmod 600 $HOME/.ssh/known_hosts
        
      - name: Copy files to EC2 instance
        run: scp -r ./metadata_ingestion ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/MyDataHubProject

      - name: Check for changes in glossary_yaml_ingestion
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^metadata_ingestion/glossary_yaml_ingestion/'; then
            echo "contains_glossary_yaml=true" >> $GITHUB_ENV
          fi

      - name: Check for changes in map_csv_ingestion
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^map_csv_ingestion/'; then
            echo "contains_map_csv=true" >> $GITHUB_ENV
          fi

      - name: Run DataHub ingest command for creating business glossary terms/term groups
        if: env.contains_glossary_yaml == 'true'
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/MyDataHubProject/glossary_yaml_ingestion && cat recipe.yml"

      - name: Run DataHub ingest command for mapping terms/tags to snowflake entity
        if: env.contains_map_csv == 'true'
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/MyDataHubProject/map_csv_ingestion && cat recipe.yml"
